[package]
name = "auto_heckin_texture_converter"
version = "5.1.0"
edition = "2021"

[dependencies]
ispc-texcomp = "0.1.20"
image = "0.24.4"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.42.0", features = ["Win32_System_Console"] }

[features]
ispc = ["ispc-texcomp/ispc"]

[profile.release]
strip = true
codegen-units = 1
lto = true
